name: Admin - Reset repo

on:
  workflow_dispatch:
    inputs:
      to_name:
        description: 'To name'
        required: true

# Reference: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  contents: write

jobs:
  reset:
    name: Reset repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Grabs all branches
          token: ${{ secrets.GH_TRAINING_TOKEN }}

      - name: Commit changes
        run: |
          # Rename main branch to main-old
          git branch -m main main-old
          git push -u origin main-old --force

          git switch develop

          # Checkout first commit in repository
          git checkout $(git rev-list --max-parents=0 HEAD)

          rm -Rf .github *

          # Restore all files from develop branch
          git checkout develop -- .

          # Create new main branch
          git switch -c main

      - name: Update client name in *.md
        run: |
          find . -type f -name "*.md" -exec sed -i "s/_CLIENT_NAME_/${{ inputs.to_name }}/g" {} +

      - name: Update client name in *.html
        run: |
          find . -type f -name "*.html" -exec sed -i "s/$_CLIENT_NAME_/${{ inputs.to_name }}/g" {} +

      - name: Set step to 0
        run: echo "0" > ./.github/steps/-step.txt

      - name: Commit changes
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

          git add .
          git commit -m "Reinitialized repository for ${{ inputs.to_name }}" --amend
          git push origin main --force